# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robolectric
email: robolectric@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  test-drive your Android code
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robolectric.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Robolectric
github_username: robolectric

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

menu:
  - title: Setup
  - title: User Guide
  - title: Customizing
  - title: Contributing
  - title: Resources
    items:
    - title: GitHub
      url: https://github.com/robolectric/robolectric/
    - title: Release Notes
      url: https://github.com/robolectric/robolectric/releases/
    - title: Migration Guide
      url: /migrating
    - title: Javadoc
      url: /javadoc/latest/
    - title: Issues
      url: https://github.com/robolectric/robolectric/issues/

whitelist:
  - jekyll-redirect-from

show_drafts: true

#source: source
permalink: "/blog/:year/:month/:day/:title/"

google_analytics: 'UA-19269905-2'

#disqus:
#  shortname: robolectric

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"


robolectric:
  version:
    current: "3.8"
    preview: "4.0-beta-1"
    snapshot: "4.0-beta-2-SNAPSHOT"
