name: Publish javadoc

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of Robolectric"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-javadoc:
    name: Publish javadoc
    runs-on: ubuntu-latest

    steps:
      - name: Extract Robolectric version
        id: robolectric_version
        run: |
          if [[ "${{ inputs.version }}" =~ ^(([0-9]+\.[0-9]+)(\.[0-9]+)?)$ ]]; then
            robolectricMinorVersion="${BASH_REMATCH[2]}"
            robolectricPatchVersion="${BASH_REMATCH[1]}"

            echo "minorVersion=$robolectricMinorVersion" > $GITHUB_OUTPUT
            echo "patchVersion=$robolectricPatchVersion" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Robolectric
        uses: actions/checkout@v6
        if: ${{ steps.robolectric_version.outputs.patchVersion }}
        with:
          repository: robolectric/robolectric
          path: robolectric
          ref: robolectric-${{ steps.robolectric_version.outputs.patchVersion }}

      - name: Checkout robolectric.github.io
        uses: actions/checkout@v6
        if: ${{ steps.robolectric_version.outputs.minorVersion }}
        with:
          path: robolectric.github.io

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        if: ${{ steps.robolectric_version.outputs.minorVersion }}
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Assemble and aggregate javadoc
        if: ${{ steps.robolectric_version.outputs.minorVersion }}
        run: |
          cd robolectric
          ./gradlew clean aggregateDocs

      - name: Move the new javadoc
        if: ${{ steps.robolectric_version.outputs.patchVersion }}
        run: |
          cd robolectric.github.io
          targetFolder="docs/javadoc/${{ steps.robolectric_version.outputs.patchVersion }}"
          if [ -e $targetFolder ]; then
            rm -r $targetFolder
          fi

          mv ../robolectric/build/docs/javadoc $targetFolder

      - name: Update Robolectric version in mkdocs.yml
        if: ${{ steps.robolectric_version.outputs.patchVersion }}
        run: |
          cd robolectric.github.io
          perl -i -0777 -pe 's/(robolectric:\s*version:\s*current: )".*"/\1"${{ steps.robolectric_version.outputs.patchVersion }}"/' mkdocs.yml
          sed -i 's/^\(    - "Javadoc":\)$/\1\n      - "${{ steps.robolectric_version.outputs.patchVersion }}": \/javadoc\/${{ steps.robolectric_version.outputs.patchVersion }}\//' mkdocs.yml

      - name: Update latest javadoc symbolic link
        if: ${{ steps.robolectric_version.outputs.patchVersion }}
        run: |
          cd robolectric.github.io
          ln -sfn ${{ steps.robolectric_version.outputs.patchVersion }} docs/javadoc/latest

      - name: Create Pull Request
        if: ${{ steps.robolectric_version.outputs.patchVersion }}
        env:
          GH_TOKEN: ${{ secrets.ROBOLECTRIC_PAT }}
        run: |
          cd robolectric.github.io
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b publish-javadoc-robolectric-${{ steps.robolectric_version.outputs.patchVersion }}
          git add -A
          git commit -m "Publish javadoc for Robolectric ${{ steps.robolectric_version.outputs.patchVersion }}" \
            -m "- Add javadoc for Robolectric ${{ steps.robolectric_version.outputs.patchVersion }}." \
            -m "- Update mkdocs.yml to add a navigation entry to the new javadoc." \
            -m "- Update mkdocs.yml to use version ${{ steps.robolectric_version.outputs.patchVersion }}."
          git push --set-upstream origin publish-javadoc-robolectric-${{ steps.robolectric_version.outputs.patchVersion }}
          gh pr create --fill
