name: "Validate snippets"

on:
  pull_request:
    paths:
      - "snippets/**"
  push:
    branches: [ main ]
    paths:
      - "snippets/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_snippets:
    name: "Validate snippets"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            snippets

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Check codestyle
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          files: snippets/**/*.java
          skip-commit: true

      - name: Print codestyle issues
        run: git --no-pager diff --exit-code

      - name: Build
        run: |
          cd snippets
          ./gradlew check
